{
 "title": "Example Dashboard",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"app\"}) by (area)",
     "legendFormat": "{{area}} usage"
    }
   ]
  },
  {
   "title": "GC Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[5m])",
     "legendFormat": "GC Frequency: {{cause}}"
    }
   ]
  },
  {
   "title": "SlowController",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "wait_times_seconds_sum / wait_times_seconds_count",
     "legendFormat": "Mean wait time"
    },
    { "expr": "wait_times_seconds_max", "legendFormat": "Max wait time" }
   ]
  },
  {
   "title": "Greeting Controller",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "name_length_sum / name_length_count",
     "legendFormat": "Mean name length"
    },
    {
     "expr": "histogram_quantile(0.80, name_length_bucket)",
     "legendFormat": "80-percentile of name length"
    },
    { "expr": "name_length_max", "legendFormat": "Max name length" }
   ]
  }
 ]
}